# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: syamak/tinyurl
        registry: docker.io
        dockerfile: ./dockerfile
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    env:
      CI: true
      MONGO_PRODUCTION_URL: ${{ secrets.PRODUCTION_DB_URL }}
      MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}
      BASE_URL: ${{ secrets.BASE_URL }}
      PORT: 5000 
      NODE_ENV: test
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET }}
